# Generated by Django 3.0.1 on 2019-12-24 15:39

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('summary', models.TextField(verbose_name='Resumo')),
                ('image', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Conteúdo')),
                ('public', models.BooleanField(default=False, verbose_name='Postagem pública')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Postado em')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
